import QuantLib as ql
from typing import Dict

from core.CurveBuilding.IRSwaps.tenor_utils import OIS_GRID, IRS_GRID_STD, IRS_GRID_LONG, IRS_GRID_10Y, IRS_GRID_15Y

SwapCurveParamsType = Dict[str, Dict[str, ql.SwapIndex | bool | ql.DayCounter | ql.Calendar | int | int | ql.Period | ql.Currency | int | int]]

CME_IRSWAP_CURVE_QL_PARAMS: SwapCurveParamsType = {
    "USD-SOFR-1D": {
        "swapIndex": ql.Sofr,
        "is_ois": True,
        "dayCounter": ql.Actual360(),
        "calendar": ql.UnitedStates(ql.UnitedStates.GovernmentBond),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.USDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": OIS_GRID,
    },
    "USD-FEDFUNDS": {
        "swapIndex": ql.FedFunds,
        "is_ois": True,
        "dayCounter": ql.Actual360(),
        "calendar": ql.UnitedStates(ql.UnitedStates.FederalReserve),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.USDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": OIS_GRID,
    },
    "USD-OIS-1D": {
        "swapIndex": ql.FedFunds,
        "is_ois": True,
        "dayCounter": ql.Actual360(),
        "calendar": ql.UnitedStates(ql.UnitedStates.FederalReserve),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.USDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": OIS_GRID,
    },
    "CAD-CORRA": {
        "swapIndex": ql.Corra,
        "is_ois": True,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Canada(ql.Canada.TSX),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("1D"),
        "currency": ql.CADCurrency(),
        "paymentLag": 2,
        "settlementDays": 0,
        "default_tenors": OIS_GRID,
    },
    "GBP-SONIA": {
        "swapIndex": ql.Sonia,
        "is_ois": True,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.UnitedKingdom(ql.UnitedKingdom.Settlement),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.GBPCurrency(),
        "paymentLag": 0,
        "settlementDays": 0,
        "default_tenors": OIS_GRID,
    },
    "EUR-ESTR": {
        "swapIndex": ql.Estr,
        "is_ois": True,
        "dayCounter": ql.Actual360(),
        "calendar": ql.TARGET(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.EURCurrency(),
        "paymentLag": 0,
        "settlementDays": 2,
        "default_tenors": OIS_GRID,
    },
    "EUR-EURIBOR-1M": {
        "swapIndex": ql.Euribor1M,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.TARGET(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1M"),
        "currency": ql.EURCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_LONG,
    },
    "EUR-EURIBOR-3M": {
        "swapIndex": ql.Euribor3M,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.TARGET(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("3M"),
        "currency": ql.EURCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_LONG,
    },
    "EUR-EURIBOR-6M": {
        "swapIndex": ql.Euribor6M,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.TARGET(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("6M"),
        "currency": ql.EURCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_LONG,
    },
    "JPY-TONAR": {
        "swapIndex": ql.Tona,
        "is_ois": True,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Japan(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.JPYCurrency(),
        "paymentLag": 0,
        "settlementDays": 0,
        "default_tenors": OIS_GRID,
    },
    "AUD-BBSW-3M": {
        "swapIndex": ql.Bbsw3M,
        "is_ois": False,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Australia(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Quarterly,
        "period": ql.Period("3M"),
        "currency": ql.AUDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_STD,
    },
    "AUD-BBSW-6M": {
        "swapIndex": ql.Bbsw6M,
        "is_ois": False,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Australia(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("6M"),
        "currency": ql.AUDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
    },
    "AUD-AONIA": {
        "swapIndex": ql.Aonia,
        "is_ois": True,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Australia(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.AUDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": OIS_GRID[:-1],  # 50Y doesnt trade
    },
    # "HKD-HIBOR-3M": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.HongKong(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Quarterly, # Or Annual for swaps
    #     "period": ql.Period("3M"),
    #     "currency": ql.HKDCurrency(),
    #     "paymentLag": 2,
    #     "settlementDays": 2,
    # },
    "NZD-BKBM-3M": {
        "swapIndex": ql.Bkbm3M,
        "is_ois": False,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.NewZealand(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Quarterly,
        "period": ql.Period("3M"),
        "currency": ql.NZDCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_STD,
    },
    "ZAR-JIBAR-SAFEX-3M": {
        "swapIndex": ql.Jibar,
        "is_ois": False,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.SouthAfrica(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Quarterly,
        "period": ql.Period("3M"),
        "currency": ql.ZARCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_15Y,
    },
    # "MXN-FTIIE-1D": {
    #     "swapIndex":
    #     "is_ois": True,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Mexico(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual, # TIIE OIS fixed leg typically annual
    #     "period": ql.Period("1D"),
    #     "currency": ql.MXNCurrency(),
    #     "paymentLag": 1, # CME TIIE Swaps
    #     "settlementDays": 1, # CME TIIE Swaps
    # },
    # "MXN-TIIE-28D": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Mexico(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Custom, # Resets every 28 days. Swap fixed leg could be Annual/SA.
    #     "period": ql.Period("28D"),
    #     "currency": ql.MXNCurrency(),
    #     "paymentLag": 1,
    #     "settlementDays": 1,
    # },
    # "INR-MIBOR-1D": { # For MIBOR OIS
    #     "swapIndex": ql.Mibor,
    #     "is_ois": True,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.India(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.INRCurrency(),
    #     "paymentLag": 2,
    #     "settlementDays": 2,
    # },
    # "KRW-CD-3M": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.SouthKorea(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Quarterly,
    #     "period": ql.Period("3M"),
    #     "currency": ql.KRWCurrency(),
    #     "paymentLag": 2,
    #     "settlementDays": 2,
    # },
    "KRW-CD": {
        "swapIndex": ql.Kofr,
        "is_ois": True,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.SouthKorea(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Annual,
        "period": ql.Period("1D"),
        "currency": ql.KRWCurrency(),
        "paymentLag": 1,
        "settlementDays": 1,
        "default_tenors": OIS_GRID[:-5],  # practical liquidity only out to 10 Y
    },
    # "CLP-CLICP-1D": {
    #     "swapIndex": ql.CLPCLICP,
    #     "is_ois": True,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Chile(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.CLPCurrency(),
    #     "paymentLag": 0, # CME ICP Swaps
    #     "settlementDays": 0, # CME ICP Swaps
    # },
    # "CNY-CNRR-1D": {
    #     "swapIndex": ,
    #     "is_ois": True,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.China(ql.China.IB),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.CNYCurrency(),
    #     "paymentLag": 1, # CME CNY swaps
    #     "settlementDays": 1, # CME CNY swaps
    # },
    # "CNY-CNRR-1W": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.China(ql.China.IB),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Custom, # Weekly fixing, swap freq would differ
    #     "period": ql.Period("1W"),
    #     "currency": ql.CNYCurrency(),
    #     "paymentLag": 1,
    #     "settlementDays": 1,
    # },
    # "COP-COLIBR-1D": { # IBR (Overnight)
    #     "swapIndex":
    #     "is_ois": True,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.Colombia(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.COPCurrency(),
    #     "paymentLag": 0, # CME IBR Swaps
    #     "settlementDays": 0, # CME IBR Swaps
    # },
    "DKK-CIBOR-6M": {
        "swapIndex": ql.DKKLibor,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.Denmark(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("6M"),
        "currency": ql.DKKCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_10Y,
    },
    # "NOK-NIBOR-6M": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Norway(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Semiannual,
    #     "period": ql.Period("6M"),
    #     "currency": ql.NOKCurrency(),
    #     "paymentLag": 2,
    #     "settlementDays": 2,
    # },
    "SEK-STIBOR-3M": {
        "swapIndex": ql.SEKLibor,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.Sweden(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Quarterly,
        "period": ql.Period("3M"),
        "currency": ql.SEKCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_STD[:-1],
    },
    "CZK-PRIBOR-6M": {
        "swapIndex": ql.Pribor,
        "is_ois": False,
        "dayCounter": ql.Actual360(),
        "calendar": ql.CzechRepublic(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("6M"),
        "currency": ql.CZKCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_10Y,
    },
    # "HUF-BUBOR-6M": {
    #     "swapIndex":
    #     "is_ois": False,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Hungary(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Semiannual,
    #     "period": ql.Period("6M"),
    #     "currency": ql.HUFCurrency(),
    #     "paymentLag": 2,
    #     "settlementDays": 2,
    # },
    "PLN-WIBOR-6M": {
        "swapIndex": ql.Wibor,
        "is_ois": False,
        "dayCounter": ql.Actual365Fixed(),
        "calendar": ql.Poland(),
        "businessConvention": ql.ModifiedFollowing,
        "frequency": ql.Semiannual,
        "period": ql.Period("6M"),
        "currency": ql.PLNCurrency(),
        "paymentLag": 2,
        "settlementDays": 2,
        "default_tenors": IRS_GRID_10Y,
    },
    # "CHF-SARON-1D": {
    #     "swapIndex": , # TODO index needs to be exposed to ql SWIG
    #     "is_ois": True,
    #     "dayCounter": ql.Actual360(),
    #     "calendar": ql.Switzerland(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.CHFCurrency(),
    #     "paymentLag": 0,
    #     "settlementDays": 2,
    # },
    # "SGD-SORA-1D": {
    #     "swapIndex":
    #     "is_ois": True,
    #     "dayCounter": ql.Actual365Fixed(),
    #     "calendar": ql.Singapore(),
    #     "businessConvention": ql.ModifiedFollowing,
    #     "frequency": ql.Annual,
    #     "period": ql.Period("1D"),
    #     "currency": ql.SGDCurrency(),
    #     "paymentLag": 0, # CME SORA
    #     "settlementDays": 2, # CME SORA
    # },
}
